### ISSUE TITLE
Remover do try cat

### ISSUE THREAD

**Issue by 0bvim** [EvertonVaz/webserv#16]
Não está usando o try cat para nada aqui, isso poder ficar fora desse bloco visto que encerra o programa quando entra na condição do `if`

https://github.com/EvertonVaz/webserv/blob/dd646b0c9244680dcf965293fffed7b1e61e2d15/srcs/main.cpp#L20-L22

**Comment by EvertonVaz** [comment]
A ideia dessa try era pegar os throws de dentro dos objetos, não aí nesse if....

Mas vou rever novamente se essa try é necessário, valeu pela dica
